spring:
  datasource:
    password: newslettercollector0705


gmail:
  client-id: 806487491033-43nlnqg49q9rsetnv69jhi8o2qnjbcl5.apps.googleusercontent.com
  user-id: newslettercollector77@gmail.com
  access-token: "ya29.a0AbVbY6Moq4JDODSXTdCoXbtvhoBU8YIjoAMDI7To_BnQhUWA90HiNcVVFSlbf3ursXBjjLeeLT8G74HR-tE2l128shKnNGxoESGaNmTbGWWxG-7k-bPdRdZrCi5rK16eEy7BFQhYuH0YoyHUnQrn4xWmtXJWaCgYKAXkSARISFQFWKvPlGvWEK8UUO7ewov3PXIchdg0163"
